# Generated by Django 3.2.6 on 2021-08-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expert", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expert",
            name="personal_life",
            field=models.TextField(default="default text"),
            preserve_default=False,
        ),
    ]
