# Generated by Django 3.2.6 on 2021-08-25 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expert", "0002_expert_personal_life"),
    ]

    operations = [
        migrations.AddField(
            model_name="expert",
            name="statistic",
            field=models.TextField(default="default statistic"),
            preserve_default=False,
        ),
    ]
